### ISSUE TITLE
pathon 3.8

### ISSUE THREAD

**Issue by sevu** [matthiaskrgr/woptipng#2]
Hi matthiaskrgr,

been a while.
I'm on python 3.8 now, and after finishing the program doesn't exit/return.
Trace after SIGINT:

```
137 of 137 files optimized, 1917946 bytes reduced to 1794538 bytes; -123408 bytes, -6.434%
Optimization threshold was 0.0%






^CProcess ForkPoolWorker-4:
Process ForkPoolWorker-3:
Process ForkPoolWorker-1:
Traceback (most recent call last):
Traceback (most recent call last):
File "/usr/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
self.run()
File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/usr/lib/python3.8/multiprocessing/pool.py", line 114, in worker
task = get()
File "/usr/lib/python3.8/multiprocessing/queues.py", line 356, in get
res = self._reader.recv_bytes()
File "/usr/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
self.run()
File "/usr/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
buf = self._recv_bytes(maxlength)
File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
buf = self._recv(4)
File "/usr/lib/python3.8/multiprocessing/pool.py", line 114, in worker
task = get()
File "/usr/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
chunk = read(handle, remaining)
File "/usr/lib/python3.8/multiprocessing/queues.py", line 355, in get
with self._rlock:
KeyboardInterrupt
File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
return self._semlock.__enter__()
KeyboardInterrupt
Traceback (most recent call last):
File "/usr/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
self.run()
File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
Process ForkPoolWorker-2:
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
File "/usr/lib/python3.8/multiprocessing/util.py", line 277, in _run_finalizers
finalizer()
File "/usr/lib/python3.8/multiprocessing/util.py", line 201, in __call__
res = self._callback(*self._args, **self._kwargs)
File "/usr/lib/python3.8/multiprocessing/pool.py", line 689, in _terminate_pool
cls._help_stuff_finish(inqueue, task_handler, len(pool))
File "/usr/lib/python3.8/multiprocessing/pool.py", line 674, in _help_stuff_finish
inqueue._rlock.acquire()
KeyboardInterrupt
Traceback (most recent call last):
File "/usr/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
self.run()
File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/usr/lib/python3.8/multiprocessing/pool.py", line 114, in worker
task = get()
File "/usr/lib/python3.8/multiprocessing/queues.py", line 355, in get
with self._rlock:
File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
return self._semlock.__enter__()
KeyboardInterrupt
File "/usr/lib/python3.8/multiprocessing/pool.py", line 114, in worker
task = get()
File "/usr/lib/python3.8/multiprocessing/queues.py", line 355, in get
with self._rlock:
File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
return self._semlock.__enter__()
KeyboardInterrupt
```
Edit: version is the one from the wesnoth repo

**Comment by cooljeanius** [comment]
did you figure this out?

**Comment by cooljeanius** [comment]
@Elvish-Hunter might have a solution...

**Comment by Elvish-Hunter** [comment]
> @Elvish-Hunter might have a solution...

*Might* being the keyword here, because I haven't tested it. It's just the result of a quick search, which suggested that subprocesses might be created recursively when using the `multiprocessing` module.
The suggested solution is to wrap everything into the `if __name__ == "__main__"` guard.

**Comment by matthiaskrgr** [comment]
Eh... if nobody minds, I might as well rewrite this in rust :sweat_smile: 
Should be a bit faster and might even be more future proof :)

**Comment by cooljeanius** [comment]
> Eh... if nobody minds, I might as well rewrite this in rust 😅 Should be a bit faster and might even be more future proof :)

I'd rather just have the quick-and-easy fix now rather than waiting for a rewrite

**Comment by matthiaskrgr** [comment]
There's a `rust` branch now, just needs a bit of cleanup and more --debug info I think

**Comment by cooljeanius** [comment]
Please just fix the python version; there is nothing else in the wesnoth repo that requires rust currently and I would hate to add another dependency just for a simple script like this
